<template>
  <div class="home">
    <div class="content">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item :to="{ path: '/' }">Home</el-breadcrumb-item>
      </el-breadcrumb>

      <el-divider></el-divider>

      <aplayer
        autoplay
        :music="{
          title: 'Resident Evil',
          src: 'http://learn.deben.me/medias/9.mp3'
        }"
      />

    <div class="page">

      <h2>Resident Evil - Opening scene</h2><p>At the beginning of the 21st century, the Umbrella <strong style="color: rgb(255, 153, 0);">Corporation </strong>had become the largest <strong style="color: rgb(255, 153, 0);">commercial entity</strong> in the United States.</p><p>Nine out of every ten homes contain its products.</p><p>Its <strong style="color: rgb(255, 153, 0);">political </strong>and <strong style="color: rgb(255, 153, 0);">financial influence</strong> is felt everywhere.</p><p>In public, it is the world's leading <strong style="color: rgb(255, 153, 0);">supplier </strong>of computer technology, medical products, and <strong style="color: rgb(255, 153, 0);">healthcare</strong>.</p><p>Unknown, even to its own <strong style="color: rgb(255, 153, 0);">employees</strong>, its <strong style="color: rgb(255, 153, 0);">massive profits</strong> are <strong style="color: rgb(255, 153, 0);">generated </strong>by <strong style="color: rgb(255, 153, 0);">military </strong>technology, <strong style="color: rgb(255, 153, 0);">genetic experimentation </strong>and <strong style="color: rgb(255, 153, 0);">viral weaponry</strong>.</p>

    </div>
    </div>

    <div class="info">

        <h3>一、核心词汇</h3><p><strong style="color: rgb(0, 102, 204);">corporation [ˌkɔ:rpəˈreɪʃn] n.</strong> 大公司；企业</p><p><strong style="color: rgb(0, 102, 204);">commercial [kə‟mɝʃəl] adj.</strong> 商业的；贸易的</p><p><strong style="color: rgb(0, 102, 204);">entity [ˈentəti] n.</strong> 实体</p><p><strong style="color: rgb(0, 102, 204);">political [pəˈlɪtɪkəl] adj.</strong> 政治的</p><p><strong style="color: rgb(0, 102, 204);">financial [faɪˈnænʃ(ə)l adj.</strong> 金融的；财务的；财政的</p><p><strong style="color: rgb(0, 102, 204);">influence [ˈɪnfluəns] n.</strong> 影响 vt. 影响</p><p><strong style="color: rgb(0, 102, 204);">supplier [səˈplaɪər] n.</strong> 供应者；供应商</p><p><strong style="color: rgb(0, 102, 204);">healthcare [,helθkeə] n.</strong> 医疗保健</p><p><strong style="color: rgb(0, 102, 204);">employee [ɪmplɔɪˈi:] n.</strong> 雇员；员工</p><p><strong style="color: rgb(0, 102, 204);">massive [,mæsɪv] adj.</strong> 大规模的；大量的</p><p><strong style="color: rgb(0, 102, 204);">profit [ˈprɑ:fɪt] n.</strong> 利润；收益 vt.&amp;vi. 使……获利；得益；获利</p><p><strong style="color: rgb(0, 102, 204);">generate [ˈdʒenəreɪt] vt.</strong> 产生；生殖</p><p><strong style="color: rgb(0, 102, 204);">military [ˈmɪləteri] adj.</strong> 军事的；军用的</p><p><strong style="color: rgb(0, 102, 204);">genetic [dʒəˈnetɪk] adj.</strong> 基因的；遗传的</p><p><strong style="color: rgb(0, 102, 204);">experimentation [ɪkˌsperɪmenˈteɪʃn] n.</strong> 实验；试验</p><p><strong style="color: rgb(0, 102, 204);">viral [ˈvaɪrəl] adj.</strong> 病毒的</p><p><strong style="color: rgb(0, 102, 204);">weaponry [ˈwepənri] n.</strong> 武器（总称）</p>

        <h3>二、核心表达</h3><p><strong style="color: rgb(255, 153, 0);">at the beginning of</strong> …… 的开始</p><p><strong style="color: rgb(255, 153, 0);">commercial entity</strong> 商业实体</p><p><strong style="color: rgb(255, 153, 0);">nine out of ten</strong> 十之有九</p><p><strong style="color: rgb(255, 153, 0);">political and financial influence</strong> 在政商两界的影响力</p><p><strong style="color: rgb(255, 153, 0);">in public</strong> 公开，当众</p><p><strong style="color: rgb(255, 153, 0);">leading supplier of</strong> （某个领域的）领军供应者</p><p><strong style="color: rgb(255, 153, 0);">massive profits</strong> 巨额利润</p><p><strong style="color: rgb(255, 153, 0);">be generated by</strong> 由……产生</p>
        
        <h3>四、参考译文</h3><p><strong>生化危机—开场白</strong></p><p>21 世纪初，“保护伞公司”已经成为全美商界的霸主。</p><p>有九成家庭采用其产品。它 在政商两界的影响力无处不在。</p><p>表面上，它是全球首屈一指的电脑技术、医疗保 健品的供应商。</p><p>暗中，就连它内部员工都不知道，它的庞大利润来源 于军事技术、基因实验和细菌武器。</p>

    </div>

  </div>
</template>

<script>

import Aplayer from 'vue-aplayer'

export default {
  name: 'Lesson9',
  components: {
    Aplayer
  }
}
</script>
